### ISSUE TITLE
Upload BPDM OpenAPI documents to Tractus-X OpenAPI-Hub

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#1012]
BPDM's REST APIs should be published to https://eclipse-tractusx.github.io/api-hub/ via the automated process from https://github.com/eclipse-tractusx/api-hub.

**Comment by nicoprow** [comment]
@SujitMBRDI what is the current status on that one? Is that something we can accomplish for this release?

**Comment by SujitMBRDI** [comment]
Hi @nicoprow, I doubt about accomplishment for this release. As [This](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1020) pull request has IPcheck issue created and which is still review state.

**Comment by nicoprow** [comment]
@SujitMBRDI Since this issue is for documentation I will keep it open for now. We have a longer time frame for providing release documentation even after the E2E tests have been done

**Comment by SujitMBRDI** [comment]
> @SujitMBRDI Since this issue is for documentation I will keep it open for now. We have a longer time frame for providing release documentation even after the E2E tests have been done

That will be good then meanwhile I shall try to seek approvals asap.

**Comment by nicoprow** [comment]
We implemented a way to continuously upload our APIs to the api-hub. They are currently uploaded there
