### ISSUE TITLE
QG checks [BPDM] (Release 24.12)

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/bpdm#1082]
## QG checks

Please open and fill in this issue in your product repository to document the compliance with our Tractus-X Release Guideline (TRGs)

**Show compliance with TRGs** by referencing to a tagged link in the respective repository where possible, example: TRG 1.01 (see [github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md](https://github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md))

### Close this issue once the compliance with the TRGs has been documented

Committer(s): @nicoprow, @SujitMBRDI 
Helm Chart Version: 5.2.0
App Version: 6.2.0

Release Management Reference Issue: 

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/)
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md`
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files
- [x] [TRG 1.05](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-05) architecture docs
- [x] [TRG 1.06](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-06) administrator guide
- [x] [TRG 1.07](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-07) user manual
- [x] [TRG 1.08](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08) open api docs

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format
- [x] [TRG 2.06](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-6) Dependabot

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim or database dependency (subchart) are in place when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information
- [x] [TRG 4.07](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07) root file system is set to read access by default, but can be overwritten by the user

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation (non-code)
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

#### TRG 8 Security
- [x] [TRG 8.01](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01) Mitigate high and above findings in CodeQL
- [x] [TRG 8.02](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02) Mitigate high and above findings in KICS
- [x] [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04) Mitigate high and above findings in Trivy
- [x] [TRG 8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) No secret findings by GitGuardian or TruffleHog

#### TRG 9 UX/UI Styleguide
- [x] [TRG 9.01](https://eclipse-tractusx.github.io/docs/release/trg-9/trg-9-01) UI consistency/styleguide for UI

**Comment by nicoprow** [comment]
Conditions Met:
[TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2): BPDM does not use own persistence but relies on greenlit bitnami postgres dependency
[TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02): All BPDM [docker imgages](https://github.com/eclipse-tractusx/bpdm/tree/release/6.2.x/docker) use base image of 21-jre-alpine
[TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03): USER command in place with user IDs and name that that can be changed by build arguments (all non-root)
[TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05): [workflow](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/.github/workflows/deploy-docker-all.yaml) deploys docker images to dockerhub (for example https://hub.docker.com/r/tractusx/bpdm-pool)
[TRG 4.07](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07): [default bpdm chart values](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/.github/workflows/deploy-docker-all.yaml) set the root file system to read only but can be overwritten
[TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01): [Helm chart](https://github.com/eclipse-tractusx/bpdm/tree/release/6.2.x/charts/bpdm) general requirements are met
[TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02): Helm charts in [correct directoy](https://github.com/eclipse-tractusx/bpdm/tree/release/6.2.x/charts/)
[TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03): Semantic versioning for [helm chart](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/charts/bpdm/Chart.yaml) version and app version in place
[TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04): [Default values](https://github.com/eclipse-tractusx/bpdm/blob/3c3e60392dccfc2d678e9d592d71c402801def30/charts/bpdm/charts/bpdm-pool/values.yaml#L64) set propery memory and cpu limits that are enough for setting up the Charts
[TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06): [Chart values](https://github.com/eclipse-tractusx/bpdm/blob/3c3e60392dccfc2d678e9d592d71c402801def30/charts/bpdm/charts/bpdm-pool/values.yaml#L122) provide application and secret config yaml properies to override the application configuration
[TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07): [Chart dependencies](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/charts/bpdm/Chart.yaml) are [configured to work](https://github.com/eclipse-tractusx/bpdm/blob/3c3e60392dccfc2d678e9d592d71c402801def30/charts/bpdm/values.yaml#L58) out of the box when installing BPDM and the Postgres version matches the aligned release guideline version
[TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08): BPDM comes with one [BPDM](https://github.com/eclipse-tractusx/bpdm/tree/release/6.2.x/charts/bpdm) helm chart in which all BPDM applications are deplyoed
[TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09): In BPDM charts are tested separately in a [liniting test workflow](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/.github/workflows/chart-test-lint.yaml) and a [chart install and upgrade workflow](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/.github/workflows/app-test-charts.yaml), covering all aspects of this TRG
[TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11): [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) provides an upgradability test which fulfills this TRG

Conditions Not Met:
[TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01): Semantic versioning in place and guaranteed by workflow. I hold of checking the check mark though until after we have released to provide it in dockerhub
[TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10): The [chart install and upgrade workflow](https://github.com/eclipse-tractusx/bpdm/blob/release/6.2.x/.github/workflows/app-test-charts.yaml) comes with the configuration to test in different kubernetes versions. This has not been done yet and the workflow needs to be upgraded

**Comment by nicoprow** [comment]
@stephanbcbauer regarding [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) we noticed that we do not have CC-BY-4.0 copyright headers on our documentation files. However, we adhered to [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) and added the necessary notices in those files (for example [here](https://github.com/eclipse-tractusx/bpdm/blob/main/INSTALL.md#notice)). 

The TRGs read like you need both the notice section and the copyright headers but that feels excessive. Also it seems tractusx repos are quite split on the matter. Do you have an insight regarding this?

**Comment by HeyHardy** [comment]
corresponding release check https://github.com/eclipse-tractusx/sig-release/issues/984

**Comment by nicoprow** [comment]
> @stephanbcbauer regarding [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) we noticed that we do not have CC-BY-4.0 copyright headers on our documentation files. However, we adhered to [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) and added the necessary notices in those files (for example [here](https://github.com/eclipse-tractusx/bpdm/blob/main/INSTALL.md#notice)).
> 
> The TRGs read like you need both the notice section and the copyright headers but that feels excessive. Also it seems tractusx repos are quite split on the matter. Do you have an insight regarding this?

@stephanbcbauer do you have a quick insight on this?

**Comment by HeyHardy** [comment]
https://catena-x.atlassian.net/browse/CXTM-1260 
E2E test is done. 
![image](https://github.com/user-attachments/assets/f69210a9-44ac-4987-aa6f-ca82c61fb713)

**Comment by nicoprow** [comment]
## CONDITION MET

[TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05): Now legal docs are also included into distribution for Orchestrator and Cleaning Service Dummy

**Comment by nicoprow** [comment]
## CONDITION MET

[TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06): Swagger UI has its own copyright as we did not create it

**Comment by nicoprow** [comment]
## CONDITION MET
[TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04): DEPENDENCIES file is up-to-date. All third party content has been IP checked

**Comment by nicoprow** [comment]
## CONDITION MET

[TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01): Apps and Charts semantically tagged on Dockerhub: 
- Pool: https://hub.docker.com/layers/tractusx/bpdm-pool/6.2.0/images/sha256-181a473b01ce8df90181c955293484b37c9cd88c6b0a8934ef96e1efff7f8ac9?context=explore
- Gate: https://hub.docker.com/layers/tractusx/bpdm-gate/6.2.0/images/sha256-3e5082d190d8df5003325f24f7523c103cbe867cedd6eafe30ca07757553880e?context=explore
- Orchestrator: https://hub.docker.com/layers/tractusx/bpdm-orchestrator/6.2.0/images/sha256-8810972de9caf806f6330d9d6a94ae925a0d23bef719c76f32d26502922925b9?context=explore
- Dummy Cleaning Service: https://hub.docker.com/layers/tractusx/bpdm-cleaning-service-dummy/6.2.0/images/sha256-5159bd97340aa7c290d7d331611414ae21074bf6e3104b4c5d9fefce57ae946b?context=explore

[TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1): Helm Chart released https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-5.2.0

**Comment by nicoprow** [comment]
## CONDITION MET

[TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10): The latest Kubernetes versions supported:
- 1.31: https://github.com/eclipse-tractusx/bpdm/actions/runs/12063714860
- 1.30: https://github.com/eclipse-tractusx/bpdm/actions/runs/12063817675
- 1.29: https://github.com/eclipse-tractusx/bpdm/actions/runs/12063948579

**Comment by nicoprow** [comment]
##CONDITION MET

[TRG 1.08](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08): APIs released on API-Hub https://eclipse-tractusx.github.io/api-hub/bpdm/6.2.0/

**Comment by nicoprow** [comment]
App 6.2.0/Chart 5.2.0 released and quality gate passed
