### ISSUE TITLE
Batch processing of task results

### ISSUE THREAD

**Issue by StWeisshaar** [eclipse-tractusx/bpdm#1092]
### Description
As BPDM architect,
I want that the Orchestrator is able to process a batch of task results that includes tasks which already proceeded into one of the next steps,
so that the batch can be processed even if there is one outdated task.

### Acceptance Criteria
- [x] A batch of task results is successfully processed even if it contains a task that already proceeded to the next step.
- [x] All open task results are processed. Outdated task results are ignored.

### Additional Information
The underlying problem is that the state maintained in the orchestrator is not always in sync with the cleaning service. This causes batches of task results to contain both records that are in need of resolution and tasks that were already resolved. Currently the whole batch is rejected without any indicator which of the provided task results is problematic. Solving the underlying problem would make this issue obsolete.

**Comment by nicoprow** [comment]
> @nicoprow Maybe the "Aborted" step state is related to our 400 error. When posting a result for an aborted task would the orchestrator return a 400 error? When using batches one aborted task could fail the whole batch. @dilipdhankecha2530 fyi

The expected behaviour for the Orchestrator is to ignore resolutions to already aborted tasks. [See test here](https://github.com/eclipse-tractusx/bpdm/blob/130c3a452cae8460669e4565be273d4aec160812/bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt#L566)

If you notice that the orchestrator still returns 400 for aborted tasks please feel free to open a nother bug issue and we will have a look into it.

**Comment by nicoprow** [comment]
@StWeisshaar recategorized this issue as a feature which will be provided in the 25.03. release. Pull request already provided (https://github.com/eclipse-tractusx/bpdm/pull/1091)

**Comment by nicoprow** [comment]
> @nicoprow The Orchestrator will only be able to ignore the aborted tasks until the retention period is reached, right? Once the retention period is over, the Orchestrator might start returning a 400 error?

Yes, a task after the retention period will be deleted. So trying to resolve a non-existing task would result in a 400 error, independent of whether it was aborted before or not. The Orchestrator does not have any information about the task anymore after the retention period

**Comment by nicoprow** [comment]
Test Case


Gate POST input/business-partners:

```json
[
  {
    "externalId": "E2E-#1092-1",
    "isOwnCompanyData": true,
    "legalEntity": {
      "legalName": "E2E-#1092-1-LE"
    },
    "address": {
      "addressType": "LegalAddress",
      "physicalPostalAddress": {
        "country": "DE",
        "city": "City 1"
      }
    }
  }
]
```

Orchestrator POST golden-record-tasks/step-reservations:
```json
{
  "amount": 1,
  "step": "CleanAndSync"
}
```

Take taskId {{TASK_ID}} from response.

**Two times**: Orchestrator POST golden-record-tasks/step-results:

```json
{
  "step": "CleanAndSync",
  "results": [
    {
      "taskId": "{{TASK_ID}}",
      "businessPartner": {
        "nameParts": [],
        "owningCompany": "{{OWNER_BPNL}}",
        "uncategorized": {
          "nameParts": [],
          "identifiers": [],
          "states": [],
          "address": null
        },
        "legalEntity": {
          "bpnReference": {
            "referenceValue": "E2E-#1092-1-LE-Ref",
            "desiredBpn": null,
            "referenceType": "BpnRequestIdentifier"
          },
          "legalName": "E2E-#1092-1-LE",
          "legalShortName": null,
          "legalForm": null,
          "identifiers": [],
          "states": [],
          "confidenceCriteria": {
            "sharedByOwner": true,
            "checkedByExternalDataSource": false,
            "numberOfSharingMembers": 1,
            "lastConfidenceCheckAt": "2023-03-20T10:23:28.194Z",
            "nextConfidenceCheckAt": "2026-03-20T10:23:28.194Z",
            "confidenceLevel": 1
          },
          "isCatenaXMemberData": false,
          "hasChanged": true,
          "legalAddress": {
            "bpnReference": {
              "referenceValue": "E2E-#1092-1-LA-Ref",
              "desiredBpn": null,
              "referenceType": "BpnRequestIdentifier"
            },
            "addressName": null,
            "identifiers": [],
            "states": [],
            "confidenceCriteria": {
              "sharedByOwner": true,
              "checkedByExternalDataSource": false,
              "numberOfSharingMembers": 1,
              "lastConfidenceCheckAt": "2023-03-20T10:23:28.194Z",
              "nextConfidenceCheckAt": "2026-03-20T10:23:28.194Z",
              "confidenceLevel": 1
            },
            "physicalAddress": {
              "geographicCoordinates": {
               "longitude": null,
               "latitude": null,
               "altitude": null
              },
              "country": "DE",
              "administrativeAreaLevel1": null,
              "administrativeAreaLevel2": null,
              "administrativeAreaLevel3": null,
              "postalCode": null,
              "city": "City 1",
              "district": null,
              "street": {
                "name": "Legal Address Street",
                "houseNumber": null,
                "houseNumberSupplement": null,
                "milestone": null,
                "direction": null,
                "namePrefix": null,
                "additionalNamePrefix": null,
                "nameSuffix": null,
                "additionalNameSuffix": null
              },
              "companyPostalCode": null,
              "industrialZone": null,
              "building": null,
              "floor": null,
              "door": null,
              "taxJurisdictionCode": null
            },
            "alternativeAddress": null,
            "hasChanged": true
          }
        },
        "additionalAddress": null
      },
      "errors": [
      ]
    }
  ]
}
```
Both requests should return 204.
