### ISSUE TITLE
Current source for ISO 3166-2 subdivision incomplete

### ISSUE THREAD

**Issue by Sebastian-Wurm** [eclipse-tractusx/bpdm#1099]
### Current Behavior
At least the following countries are incomplete in the [current source](https://github.com/eclipse-tractusx/bpdm/blob/e230e997dc43db77b096ee45f927d9ab8a26c68e/bpdm-pool/src/main/resources/regions/IP2LOCATION-ISO3166-2.CSV) regarding ISO 3166-2 subdivision codes, see
- [GB - United Kingdom of Great Britain and Northern Ireland (the)](https://www.iso.org/obp/ui/#iso:code:3166:GB)
- [ES - Spain](https://www.iso.org/obp/ui/#iso:code:3166:ES)
- [FR - France](https://www.iso.org/obp/ui/#iso:code:3166:FR)

### Expected Behavior
Another source must be found. Best integrate the primary ISO source directly using the corresponding up-to-date [ISO product](https://www.iso.org/publication/PUB500001.html).

### Steps To Reproduce
Check the CSV source for e.g. GB-YOR.

**Comment by nicoprow** [comment]
@Sebastian-Wurm Scheduled the fix for the next release as it is currently unclear which source we can take to fix the gap.

**Comment by nicoprow** [comment]
@maximilianong @Sebastian-Wurm I removed myself from this issue as there is no development task at the moment.
We need to find a definition for the missing administrative areas. Who drives this topic to the refined state?

**Comment by Sebastian-Wurm** [comment]
> @maximilianong @Sebastian-Wurm I removed myself from this issue as there is no development task at the moment. We need to find a definition for the missing administrative areas. Who drives this topic to the refined state?

I presented this issue in the BPDM Expert Group. Cofinity-X promised to come up with a solution.

**Comment by maximilianong** [comment]
On upstream we will stay with the existing solution. The operator will provide the list from an payed provider.
