### ISSUE TITLE
Missing output stage for same external_id but different tenant_bpnl

### ISSUE THREAD

**Issue by StWeisshaar** [eclipse-tractusx/bpdm#1104]
### Current Behavior
When sending back data back to the Gate, we saw success in the sharing state, but no output stage was generated. We found the root cause, shown in the screenshot below. This issue happens when we get the same external IDs with different tenant values.

![image](https://github.com/user-attachments/assets/cd4d8f5c-3ae1-498b-9a56-1395e1405d3e)

Props to @dilipdhankecha2530 for finding this issue!

### Expected Behavior
Even though there is already an output stage for the given external ID, a new output stage is generated in case the tenant value is different.

### Steps To Reproduce
1. Process a new dataset with external ID = A and tenant value = null
2. Wait for the dataset to create an output stage
3. Process a new dataset with the same external ID = A and tenant value != null
4. There is no separate output stage created for the second dataset

**Comment by dilipdhankecha2530** [comment]
https://github.com/eclipse-tractusx/bpdm/pull/1109

**Comment by nicoprow** [comment]
resolved in https://github.com/eclipse-tractusx/bpdm/pull/1109.
