### ISSUE TITLE
Business Partner Type Matching Clarifications

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#1110]
I would like to use this issue to sharpen expectations and requirements for the golden record refinement process. Basically, I noticed that I have some doubts on the exact expected behaviour when it comes to the refinement of business partner data. That is why I want to put out some questions to you regarding your understanding and expectations.

### Definitions

- Legal Entity: Business partner data describing a legal entity including the legal address (golden record legal entity identified by BPNL)
- Site: Business partner data describing a site including the site main address (golden record site identified by BPNS)
- Additional Address: Business partner data describing a logistic address belonging to a legal entity and optionally also belonging to a site. Important: The additional address is a type of address which is not a legal address or a site main address (golden record additional address identified by BPNA )

### Statements

In the following are statements about sharing business partner data and matching the shared data to the golden record counterparts. Please give a feedback which options are correct in your opinion for:

A. Own Company Data
B. Data for Another Company

#### Legal Entity

1. I share a legal entity and I expect the golden record process to find me the correct legal entity data, meaning: Find me the legal entity matching this data." For example, I could specify a legal entity by wrongfully giving an additional address as the legal address. The golden record process recognizes that this is an additional address of a legal entity. Since the record was shared as a legal entity, the process will match this record to the BPNL instead of to the BPNA.
 -- or --
2. I share a legal entity and I expect the golden record process to find me any matching business partner data, meaning: "Find me the golden record (BPNA, BPNS or BPNL) matching this data." For example,  I could wongfully specify a legal entity by giving an additional address as the legal address. The golden record process should match this to the additional address with a BPNA, saying "The business partner data you entered seems not to be a legal entity but actually an additional address".

#### Additional Address

1. I share an additional address and I expect the golden record process to find me the correct **additional address** data, meaning: Find me the additional address matching this data." For example, I could specify an additional address by wrongfully giving legal address data. The golden record process recognizes that this is the legal address of a legal entity. Since the record was shared as an additional address, the process reports that no match can be made as there is no additional address to be found.
 -- or --
2. I share an additional address and I expect the golden record process to find me the correct **address** data, meaning: Find me the address (any BPNA) matching this data." For example, I could specify an additional address by wrongfully giving legal address data. The golden record process recognizes that this is the legal address of a legal entity. The process matches the record to the legal address BPNA, stating that the additional address is actually a legal address.
 -- or --
3. I share an additional address and I expect the golden record process to find me **any matching business partner data**, meaning: "Find me the golden record (BPNA, BPNS or BPNL) matching this data." For example,  I could wongfully specify an additional address that is actually a legal address. The golden record process recognizes the legal address and matches the record to the BPNL, stating "The additional address you shared is actually a legal address and thus is better described as a legal entity".

**Comment by nicoprow** [comment]
> Discussion results of today's BPDM Expert group meeting (20.11.24): Case1 : Not being the data owner
> 
> Normally there would be no pre-definition of a BP as additional address or legal entity. In case one sharing member (who is not the data owner) provides this information it should be ignored and treated like as there is no information. This is necessary as this information should only be contributed by the "real" data owner or being derived in the course of GR processing (by e.g. lookup in external data sources).
> 
> In case of pre-defining BP as legal entities and additional addresses we would expect that the GR content replaces the content of the shared data --> Option 2 above (for L-scenario) respectively option 3 (for A-scenario)
> 
> Case 2: Being the data owner
> 
> In this case the expectation is that the data owner knows the shared data best (which also leads to a higher confidence level). Such own data should nevertheless be processed with DQ rules, lookup/enrichments (no GR Process "Bypass") in order to calculate a comprehensive confidence level and also to identify possible deviations between external data sources and the initially owner-shared content.

Thank you for the answers!

Does that mean for case 2: Is it possible that a data owner shares a legal entity but the golden record process returns an additional address instead as output?

**Comment by zygokaktus** [comment]
@nicoprow: No, here ist the assumption that the provided content of the data owner "rules". If he classifies the own data as e.g. being a legal entity and Cofinity sees it differently the data of the owner will still to be considered as truth. Nevertheless in such cases there might be a process (not yet defined) to approch the data owner for alignemnt purposes...

**Comment by nicoprow** [comment]
> [@nicoprow](https://github.com/nicoprow): No, here ist the assumption that the provided content of the data owner "rules". If he classifies the own data as e.g. being a legal entity and Cofinity sees it differently the data of the owner will still to be considered as truth. Nevertheless in such cases there might be a process (not yet defined) to approch the data owner for alignemnt purposes...

Thank you for the clarification. This answers my questions

**Comment by nicoprow** [comment]
I regard this question as answered and no follow-up questions expected. closing for now
