### ISSUE TITLE
Helm chart Version / App Version Missmatch

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#112]
Hi @nicoprow,

provided Helm chart Version differs from App Version:
Helm Chart Version Pool: 4.3.0  
App Version: 3.2.1  
https://github.com/eclipse-tractusx/bpdm/blob/0d4a4adcff343d2ef20554c55bd4edb14e1bdd2c/charts/pool/Chart.yaml#L24-L25

Helm Chart Version Gate: 3.3.0
App Version: 3.2.1  
https://github.com/eclipse-tractusx/bpdm/blob/0d4a4adcff343d2ef20554c55bd4edb14e1bdd2c/charts/gate/Chart.yaml#L24-L25

Question for me typo in requested versions or missmatch?

Thx for clearification

**Comment by nicoprow** [comment]
The Charts are now updated with the correct app version to use:

https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-gate-3.3.1
https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-pool-4.3.1

Versions:
Gate: 3.3.1
Pool: 4.3.1

App-Version: 3.3.2 (due to updates in dependency)

**Comment by FaGru3n** [comment]
closed
