### ISSUE TITLE
Licence headers

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#113]
Found some missing header information.
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02/#chart-file-structure

Pool:
https://github.com/eclipse-tractusx/bpdm/blob/bpdm-pool-4.3.0/charts/gate/templates/ingress.yaml

Gate:
https://github.com/eclipse-tractusx/bpdm/blob/bpdm-gate-3.3.0/charts/gate/templates/ingress.yaml

**Comment by nicoprow** [comment]
Trying to add license header to the ingress file breaks the deployment on argocd. I suspect its because ArgoCD uses helm v2. Here is the issue that should be relevant: https://github.com/helm/helm/issues/4409
Do you have an update or workaround for that?
