### ISSUE TITLE
LegalName for Tasks created via the partner-upload-controller 

### ISSUE THREAD

**Issue by StWeisshaar** [eclipse-tractusx/bpdm#1141]
### Description
As operator of BPDM,
I require the business partner object that can be reserved via the Orchestrator Task Worker to contain legalName or nameParts,
so that all relevant information is present.

### Acceptance Criteria
- [ ] legal entity information are fetched from the Pool based on the legalEntityBpn
- [ ] nameParts and legalName are populated based on fetched information

### Additional Information
The issue is relevant for the BP explorer context. The partner-upload-controller allows users to upload their sites and addresses. When using the csv upload feature you can not provide any legal entity information. The legal entity information for such a task is currently populated based on the BPNL that was used in authentication. Tasks created via the partner-upload-controller therefore do not contain a legalName or nameParts, but only contain a legalEntityBpn. Such tasks do not fulfill the mandatory field requirements and can create downstream issues.

- [2.1.2  UPLOAD CRITERIA AND MANDATORY FIELDS](https://catenax-ev.github.io/docs/next/standards/CX-0076-GoldenRecordEndtoEndRequirementsStandard#212-upload-criteria-and-mandatory-fields)
- [partner-upload-template.txt](https://github.com/user-attachments/files/17946549/partner-upload-template.txt)

Note: Using this endpoint companies will only be able to create sites and address for their own legal entity. This endpoint can not be used to create sites or addresses for any other legal entity. Even subsidiaries are excluded as they will generally have distinct BPNLs.

**Comment by SujitMBRDI** [comment]
Test Case:

### Update template from new data

1. Gate GET input/partner-upload-template:

    Default file name for downloaded template - partner-upload-template.csv

2. Update site information to be created in CSV file

   Sample - [partner-upload-template.csv](https://github.com/user-attachments/files/18978582/partner-upload-template.csv)


3. Gate POST output/business-partners/search:
    ```json
    [
      "E2E-#1141-1"
    ]
    ```

Verify legal entity information like legalName is being fetched
