### ISSUE TITLE
Umbrella Chart: Include Dummy Bridge Service

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#151]
Once we have an umbrella chart as described in issue #139 we should also include the BPDM dummy bridge service in this chart. That way we can deploy an independently running BPDM service. With default values the Bridge service should automatically find the pool and gate and connect with them.

Requires issue #160 first.

**Comment by fabiodmota** [comment]
done and can be review on #https://github.com/eclipse-tractusx/bpdm/pull/194
