### ISSUE TITLE
Dummy Bridge Uses Old Datamodel

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#152]
Currently the BPDM project does not compile, due to the Dummy Bridge module failing. The Bridge still works against the old API client which leads to errors.

Solution:
Update how the Bridge uses the Gate and Pool API clients to the newest version of the datamodel.

**Comment by martinfkaeser** [comment]
Fixed with https://github.com/eclipse-tractusx/bpdm/pull/166/files
