### ISSUE TITLE
Pool: Remove SaaS import logic

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#155]
Currently, the Pool contains integration logic with a SaaS provider to import business partner data. However, the Pool should be independent of a specific SaaS provider. Therefore, we should remove that logic from the Pool.

For future providers who want to integrate against the Pool, they can use the Pool API to create and update business partners.

**Comment by fabiodmota** [comment]
Done on https://github.com/eclipse-tractusx/bpdm/pull/206
