### ISSUE TITLE
Gate API: Merge Changelog Endpoints in Gate

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#241]
Currently the Gate has two changelog endpoints for querying and filtering the changelog. One for filtering by modifiedAfter time and list of external-ids. The other filters by modifiedAfter time and lsa-Type. Since external-ids are not unique to lsa-type it makes sense to merge these two endpoints together and apply all those filters together.

**Comment by rainer-exxcellent** [comment]
Looks good.
In the ChangeLogSearchRequest could be remarked, that when externalIds or the lsaTypes are empty the parameters are ignored
