### ISSUE TITLE
NameParts: Replace Array with Collection Type

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#263]
Array is a very specialized type in Kotlin and can better be replaced by the normal Collection type. Currently some namePart fields (legalNameParts) are of type Array and should be converted to the Collection Type. The resulting JSON will be unaffected.

**Comment by fabiodmota** [comment]
Waiting for review on https://github.com/eclipse-tractusx/bpdm/pull/287
