### ISSUE TITLE
Gate Auth: Configurable Permission Names

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#265]
Currently the Gate endpoints are secured via fix-named permissions. The Gate properties should offer to configure the name of permissions. Also the BpdmSecurityConfigurerAdapterImpl should secure the endpoints in the following way:

Read Input Business Partner Data: Default "read_company_input_data":
Access to all read business partner input endpoints and the changelog

Write Input Business-Partner:  Default "change_company_input_data":
Access to all PUT business partner input endpoints to change the data

Read Output Business Partner Data: Default "read_company_output_data":
Access to all read business partner output endpoint, the changelog and sharing state

Write Output Business-Partner:  Default "change_company_output_data":
Access to change the business partner output and sharing states

**Comment by fabiodmota** [comment]
waiting review on https://github.com/eclipse-tractusx/bpdm/pull/300
