### ISSUE TITLE
Gate: Implement Output Changelog

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#269]
The Gate currently has a not implemented changelog for Output business partner data. This endpoint should behave analogous to the input changelog endpoint. In order to do this, the changelog entries need an output/input type distinction like the business partners have. When a business partner output is updated a new changelog entry with the output type should be created. The output changelog then queries and filters changelog entries with the output data type.

The input changelog logic also needs to be adapted to only display changelog entries with the input data type.

**Comment by fabiodmota** [comment]
Wait review on https://github.com/eclipse-tractusx/bpdm/pull/294
