### ISSUE TITLE
Migration deletes the existing data

### ISSUE THREAD

**Issue by dilipdhankecha2530** [eclipse-tractusx/bpdm#323]
**V4_0_0_0__update_pool_datamodel.sql**

delete
from legal_entities;

**Comment by bhautik-sakhiya** [comment]
@dilipdhankecha2530  
I agree, I have also faced the same issue.

**Comment by nicoprow** [comment]
In the upcoming major version change 4.0.0 we will have many breaking changes to the data model. This lead us to the decision to have no migration from 3.x.x to 4.0.0 but rather start a clean slate data wise. We have migrations that translate the model from 3.x.x to 4.0.0 but the data will be lost.

**Comment by nicoprow** [comment]
The release came and this information was included as a disclaimer: https://github.com/eclipse-tractusx/bpdm/releases/tag/v4.0.0
