### ISSUE TITLE
BPDM Pool Search App  (ext: CXAR-1050)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/bpdm#347]
*Benefit Hypothesis & Problem Statement*

Currently there is only a search over the Portal network on BPNL´s possible.

A search on all types of Business Partner Data (L,S and A) including their relations and attributes is only possible via a technical integration against our endpoints. For the future BPDM service it is necessary to offer  a search app which provides different search options (search via different attributes).

 

To be detailed out!!!

 

 

 

 

+*Beneficiaries*+

 

_Components_: BPDM_GR
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by nicoprow** [comment]
This topic is now covered here eclipse-tractusx/sig-release#603
