### ISSUE TITLE
Country Risk Dashboard: General Improvements (ext: CXAR-1028)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/bpdm#348]
+*Benefit Hypothesis*+

The goal of this feature is to improve the general usability and user experience when using the Country Risk Dashboard.

This can be achieved through:
 * new filter functionalities
 * new sharing api´s
 * adding new languages
 * increasing readability of markers through hierarchy in L/S/A business partners
 *  

+*Beneficiaries*+

The beneficiaries would be all users of the apllication

 

+*Requirements:*+

These improvements would include, but are not limited to:
 * Filtering for L/S/A business partners globally in all components
 * pagination of loading business partners
 * edc connection to pool and gate (when both are available)
 * upgrade to newest frontend components provided by CX Portal
 * improved filter functionality in the table
 ** customer
 ** supplier
 ** textsearch
 * ...

_Components_: BPDM_COUNTRYRISK
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by nicoprow** [comment]
@Phil91 This repository is only for the BPDM service. Country risk is a value added service whose repositories you can find here: https://github.com/eclipse-tractusx/vas-country-risk and https://github.com/eclipse-tractusx/vas-country-risk-backend.

Please place this issue in the appropriate repository. I'm closing this issue for now.

**Comment by Phil91** [comment]
@nicoprow i just did run the script to migrate the issue from jira to github.
