### ISSUE TITLE
Country Risk Dashboard: Upgrade of Maps (ext: CXAR-1027)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/bpdm#349]
+*Benefit Hypothesis*+

Currently the Country Risk Apllication uses a generic, low detailed Map with the library React Simple maps.

To further improve the usability of the dashboard it is necessary to upgrade these Maps to include much more details. With this it is easier to check country specific risks or now region specific risks like floods or natural catastrophes.

 

+*Beneficiaries*+

The main beneficiaries are:
 * Compliance
 * Logistics

 

 

+*Requirements:*+

A good Example for the Map which would be a good fit is:

[](https://www.openstreetmap.de/)

 

While upgrading the Map the current functionalities need to be maintained.

These functionalities include, but are not limited to:
 * Setting markers at Geocoordinates for each available Business Partners
(only shown after certain zoomed in state)
 * "Colouring" of the countries according to the selected Ranges and Ratings
 * Hovering over countries reveals relevant Information
 ** Number of Business Partners
 ** Country Score
 ** Country name
 * Showing the Country names or ISO2 Country Code without hovering
 * Maneuveriability
 * Filtering for Countries with Business Partners
 * ...

 

_Components_: BPDM_COUNTRYRISK
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by nicoprow** [comment]
@Phil91 This repository is only for the BPDM service. Country risk is a value added service whose repositories you can find here: https://github.com/eclipse-tractusx/vas-country-risk and https://github.com/eclipse-tractusx/vas-country-risk-backend.

Please place this issue in the appropriate repository. I'm closing this issue for now.

**Comment by Phil91** [comment]
@nicoprow i just did run the script to migrate the issue from jira to github.
