### ISSUE TITLE
Generic Business Partner Datamodel

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#382]
Proposal for a generic business partner model that can be used when the actual business partner type is unknown at creation time: 

```mermaid
---
title: Generic Business Partner
---
classDiagram
    class Business_Partner{
        External ID
        Name Parts
        Short Name
        Legal Name
        Identifiers
        Legal Form
        States
        Classifications
        Roles
        Address
        Is Own Company Data
        Address BPN
        Legal Entity BPN
        Site BPN
    }
    class Identifier{
        Value
        Type
        Issuing Body
    }
    class State{
        Description
        Valid From
        Valid To
        Type
    }
    class Classification{
        Value
        Code
        Type
    }
    class Address{
        Physical Postal Address
        Alternative Postal Address
    }

    class PhysicalPostalAddress{
        Geo-Coordinates
        Country
        Admin Level 1
        Admin Level 2
        Admin Level 3
        City
        District
        Postal Code
        Company Postal Code 
        Industrial Zone
        Street Name
        Street Name Prefix
        Street Name Additional Prefix
        Street Name Suffix
        Street House Number
        Street Direction
        Street Milestone
        Building
        Floor
        Door
    }
    class AlternativePostalAddress{
        Geo-Coordinates
        Country
        Admin Level 1
        Delivery Service Number
        Delivery Service Type
        Delivery Service Qualifier
        City
        Postal Code
    }

 class AddressType{
   <<enumeration>>
    LegalAndSiteMainAddress
    LegalAddress
    SiteMainAddress
    AdditionalAddress

 }
    Business_Partner --> Identifier: Has Several
    Business_Partner --> State: Has Several
    Business_Partner --> Classification: Has Several
    Business_Partner --> Address: Can Have One
    Address --> AddressType: Can Have One
    Address --> PhysicalPostalAddress: Can Have One
    Address --> AlternativePostalAddress: Can Have One
```

Related Issues to fulfill this epic:

- [x] #384
- [x] #387 
- [x] #428
- [x] #439
- [x] #440
- [x] #441
- [x] #442
- [x] #456
- [x] #476 
- [x] #490 
- [x] #489 
- [x] #471 
- [x] #519 
- [x] #557 
- [x] #594

**Comment by Sebastian-Wurm** [comment]
@nicoprow : What would be the next steps towards implementation?

**Comment by nicoprow** [comment]
Decision: We replace the flags "legalAddress" and "siteMainAddress" inside PostalAddress with an enum  field "AddressType" having values:

1. LegalAndSiteMainAddress
2. LegalAddress
3. SiteMainAddress
4. AdditionalAddress

The enum field is required in the Output version and optional in the Input version.

**Comment by Rossisep** [comment]
Dear colleagues,

Where do I find in the Generic Endpoint the LegalForm Abbreviation?
Are the GEPO coordinates an alphanumeric string?

Best regards

Stephan

**Comment by nicoprow** [comment]
> Dear colleagues,
> 
> Where do I find in the Generic Endpoint the LegalForm Abbreviation? Are the GEO coordinates an alphanumeric string?
> 
> Best regards
> 
> Stephan

Hi @Rossisep ,

the field "Legalform" field in the generic business partner model contains the String description of the business partner's legal Form. When the sharing member specifies in the business partner in the input they can give any String description of the legal form. For the cleaning process the service provider will try to identify the legal form and replace it with the correct technical key for the legal form from the Catena network. So the output will have the legal form technical key stored in that field.

Address information of the generic business partner will stay the same as with L/S/A typed business partners. The Geo-Coordinates are a complex object. You can refer to the [Pool's OpenAPi specification](https://raw.githubusercontent.com/eclipse-tractusx/bpdm/main/docs/api/pool.yaml) or alternatively already have look into the [proposed OpenApi definitions of the generic endpoints](https://github.com/eclipse-tractusx/bpdm/issues/384).

**Comment by Korbinian-Hutter** [comment]
@nicoprow @Sebastian-Wurm we would like to change the name from "IsOwner" to "IsOwnCompanyData" to better represent the Fields meaning.

**Comment by Sebastian-Wurm** [comment]
@Korbinian-Hutter: It makes sense to make it more specific. I actually came up with the name "SharingMemberIsOwner", when I tried to find a definition for the property: "Indicates whether the sharing member is the owner of the site." What do you think about that? It would incorporate the original idea of "IsOwner", but with slightly more information.

**Comment by Korbinian-Hutter** [comment]
@Sebastian-Wurm ja passt für mich

**Comment by Sebastian-Wurm** [comment]
> @Sebastian-Wurm ja passt für mich

Which alternative of it?

**Comment by Korbinian-Hutter** [comment]
@Sebastian-Wurm I meant the first: "SharingMemberIsOwner"

**Comment by Sebastian-Wurm** [comment]
> I would like to propose to rename the BPNL and BPNS fields to "Parent BPNL" and "Parent BPNS" as this makes the nature of the generic business partner more obvious: It contains an address that will be mapped 1 to 1 with a golden record address partner having a BPNA. It also belongs to a legal entity and it may also belong to a site but while it may be a legal address or a main site address it is actually not a legal entity or a site itself.
> 
> @gerlitmcoding @Sebastian-Wurm

I agree, that the business partner IS not a legal entity or a site. I am unsure, whether the business partner really IS an address. I see the business partner in Catena-X more as a merged view of the three L/S/A entities.

**Comment by Rossisep** [comment]
Isn't it true that a BPNA represents another physical location of a Legal Entity and/or a Site. So a BPNA is a child of either/and a Parent BPNL and a Parent BPNS. So if we define Parents we should also define Childs. The substance of a Business Partner is based on his role(s).

**Comment by nicoprow** [comment]
The generic business partner data model used in the Gate and the Golden Record process has been implemented. Changes and adjustments will be dealt with in follow-up issues as necessary.
