### ISSUE TITLE
Gate API: Create Input Endpoints for Generic Business Partner

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#384]
As a sharing member I may not know which business partner type my record has. I want to share my business partner record in a generic way without needing to pre-determine its type. Which business partner type it is should be the result of the output data in the sharing process.

For this we need endpoints for the input stage that accept and deliver business partners in a generic model.

Acceptance Criteria:
 - Endpoint for uploading several business partners in a generic model
 - Endpoint for querying several business partners by external id and returning them in a generic model

This relates to the generic business partner model discussed in #382 

<img width="1401" alt="image" src="https://github.com/eclipse-tractusx/bpdm/assets/95762387/e938310f-30d1-40ed-b4b4-44c5050519b6">

[Redoc Rendering](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/eclipse-tractusx/bpdm/docs/api/generic-input/docs/api/gate-proposal.yaml)

### Tasks

- [x] Create endpoints in Gate API module
- [x] Add optional BPN fields to API model as depictied in the OpenAPI snippet

**Comment by rainer-exxcellent** [comment]
In the Open-API  snippet the put request returns an array of BusinessPartnerInputResponse in all other endpoints which creates an object we simple return an HTTP status codes. 

Is this correct?

**Comment by fabiodmota** [comment]
looks good for me , and about the returning object at least is according to the diagram variant 1 when the upsert is done 

![image](https://github.com/eclipse-tractusx/bpdm/assets/107047355/94557d9e-6cd0-4864-ba5c-448623454c68)

**Comment by nicoprow** [comment]
The generic input business partner should also have BPN fields for Legal Entity, Site and Address as is depicted in #384

**Comment by martinfkaeser** [comment]
@nicoprow 
Is it correct that for `BusinessPartnerIdentifier` DTO only the `type` is required, but not the `value` (see Redoc)?
For `LegalEntityIdentifier` DTO both `type` and `value` are required.

**Comment by nicoprow** [comment]
> @nicoprow Is it correct that for `BusinessPartnerIdentifier` DTO only the `type` is required, but not the `value` (see Redoc)? For `LegalEntityIdentifier` DTO both `type` and `value` are required.

You are right, that was an oversight. I have corrected it in the proposal.

**Comment by nicoprow** [comment]
Added a task list with showing the open topics of BPN fields in the Input DTO
