### ISSUE TITLE
Clarification: Legal info for distribution (TRG 7.05)

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/bpdm#404]
## Description 

[TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) describes, that the legal info (at least `NOTICE.md`, `DEPENDENCIES` and `LICENSE`) have to be included in the distribution artifact. In this case the .jar, that is build for the service.

Could you please verify and point out, if these files are included? I could not find a matching build config, but I also do not have good insight in your build setup.

If this is missing, it is blocking #389  

## Additional info

This [build config](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/consumer-backend/productpass/pom.xml#L189-L202) works for the digital-product-pass app, which is also maven based

**Comment by nicoprow** [comment]
The mentioned lega linfo will now be packaged into the Jar files

**Comment by SebastianBezold** [comment]
Hi @nicoprow ok great to hear. Did you build a new version, that does contain the legal info already?

**Comment by SebastianBezold** [comment]
As stated in [this comment](https://github.com/eclipse-tractusx/bpdm/issues/389#issuecomment-1696908478), the changes are included in `4.0.1` so fine with me
