### ISSUE TITLE
GATE: Array (legal)NameParts does not guarantee an order

### ISSUE THREAD

**Issue by Sebastian-Wurm** [eclipse-tractusx/bpdm#423]
# Actual behavior:
- Upload a new legal entity or update it, which has several legalNameParts, see example:
- PUT /api/catena/input/legal-entities

```json
{
    "legalNameParts": [
      "Dr. Ing. h. c. F. Porsche",   
      "Aktiengesellschaft",
      "Porsche AG",
      "Zuffenhausen, Werk 2, Pforte Lieferanten"
    ],
    //  etc.
   "externalId": "c7bf880e-c304-1edd-beda-8b99d88c1bde"
}
```
- Download the same legal entity -> legalNameParts are returned as follows
- GET /api/catena/input/legal-entities/c7bf880e-c304-1edd-beda-8b99d88c1bde

```json
{
    "legalNameParts": [
      "Aktiengesellschaft",
      "Zuffenhausen, Werk 2, Pforte Lieferanten",
      "Dr. Ing. h. c. F. Porsche",   
      "Porsche AG"
    ],
    //  etc.
   "externalId": "c7bf880e-c304-1edd-beda-8b99d88c1bde"
}
```
# Expected behavior:

- Order is maintained

**Comment by nicoprow** [comment]
The name parts array field in the generic business partner now guarantees an order and the legal entities endpoints are deprecated. So I think this issue is solved or irrelevant depending on how one looks at it.
