### ISSUE TITLE
Gate: Connect Sharing State with One-to-One Relation to Generic Business Partners

### ISSUE THREAD

**Issue by alexsilva-CGI** [eclipse-tractusx/bpdm#439]
Add a field to link to the generic Business Partner by databaseID. 

Currently, when upserting an Legal Entity, Site or Address, an new row is created in the Sharing_States table, with the corresponding BusinessPartnerType and ExternalID from the upserted L/S/A. 

Regarding the new Generic Business Partner, it will not have an BusinessPartnerType, so this field cannot be used in a creation of an new Sharing State, only the ExternalID.

~~Current question is if the BusinessPartnerType in the sharing state should be deprecated regarding this?~~

Solution: **BusinessPartnerType will be optional on Sharing_States. Direct connection between Sharing State and Generic Business Partner will be done by the ExternalID.**

**Comment by martinfkaeser** [comment]
@nicoprow 
It's not clear how SharingState and BusinessPartner should exactly be linked because for every externalId there is just one SharingState but two BusinessPartners in different stages.

**Comment by nicoprow** [comment]
At this moment we do not intend to support L/S/A endpoints entering the golden record process through the orchestrator. For this reason attaching L/S/A to the service logic is not needed.
