### ISSUE TITLE
Gate: Replace LSA Typed Service Logic with Generic Service Logic

### ISSUE THREAD

**Issue by rainer-exxcellent** [eclipse-tractusx/bpdm#440]
When a request comes in to upsert an LSA Business Partner, then it needs to be mapped to the generic model
and passed to the generic service.
The generic service already persists the data. No LSA data is persisted anymore.
Upon receiveing a GET request for an LSA Business Partner the first step is to check if the data is of the requested type.
Then take the generic data and convert it to the LSA type.

**Comment by nicoprow** [comment]
At this moment we do not intend to support L/S/A endpoints entering the golden record process through the orchestrator. For this reason attaching L/S/A to the service logic is not needed.
