### ISSUE TITLE
Timed out waiting for container port to open (localhost ports: [59400] should be listening)

### ISSUE THREAD

**Issue by fsobh** [eclipse-tractusx/bpdm#521]
### **I am trying to follow the [INSTALL.MD](https://github.com/eclipse-tractusx/bpdm/blob/main/INSTALL.md) directions for the [bpdm kit](https://github.com/eclipse-tractusx/bpdm)**

Whenever I begin by running `mvn clean install`, all my tests and tasks run fine until it reaches the tests for the [bpdm-bridge-dummy](https://github.com/eclipse-tractusx/bpdm/tree/main/bpdm-bridge-dummy)

This is the error I am running into : 
![Screenshot 2023-10-12 at 1 51 29 PM](https://github.com/eclipse-tractusx/bpdm/assets/37850797/cd659269-2db0-403a-8b54-4575219a611e)

![Screenshot 2023-10-12 at 1 53 26 PM](https://github.com/eclipse-tractusx/bpdm/assets/37850797/a41c4047-f906-4c26-a1a5-caac912e4b24)

The Error clearly states : " **Timed out waiting for container port to open (localhost ports: [59400] should be listening)** "

Even though the container at 59400 IS running : 

<img width="1409" alt="Screenshot 2023-10-12 at 1 40 25 PM" src="https://github.com/eclipse-tractusx/bpdm/assets/37850797/15ea77d5-094a-46d8-a6f1-0ab95f57123c">

Am I doing something wrong or is there a certain configuration I should be setting before running ?

PS : I am on a Mac Book Pro M1

**Comment by nicoprow** [comment]
Looks to me like you have a similar problem like #522. For executing tests on the bpdm-bridge-dummy you need to install some docker images first that will be needed for testing. The docker-compose.build.yaml will do this for you. Please have  a look here: https://github.com/eclipse-tractusx/bpdm/issues/522#issuecomment-1761051682

**Comment by nicoprow** [comment]
Answer as been given and also added to the general documentation. Hint: In the coming release 5.0.0 this behaviour will not exist anymore.
