### ISSUE TITLE
"message":"pull access denied for maven-pool, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

### ISSUE THREAD

**Issue by devbydixon** [eclipse-tractusx/bpdm#522]
Getting this error When running `mvn clean install`

Do I need permissions to run this ?

![image](https://github.com/eclipse-tractusx/bpdm/assets/131799358/b9c7249e-eca7-4206-aa63-59d17671948f)

![image](https://github.com/eclipse-tractusx/bpdm/assets/131799358/86ec01c4-683a-4608-9cbc-fe4d0c5d13af)

**Comment by nicoprow** [comment]
The mvn clean install executes integration tests which fail and result in the install to be aborted. 

The failing tests are coming from the bpdm-bridge-dummy module which needs a preliminary step for executing its tests. 

You have two options from here:

1. You can install the maven dependencies without executing the tests: `mvn clean install -DskipTests`
2. You fulfill the bpdm-bridge-dummy's precondition and install the missing docker images first: `docker compose -f docker-compose.build.yml build`. Afterwards you can just run `mvn clean install` like normal

We should adapt the documentation for the install accodingly as there is no mention of that in the README
