### ISSUE TITLE
Security Assessment: Rate Limiting for API usage on Pool and Gate

### ISSUE THREAD

**Issue by gerlitmcoding** [eclipse-tractusx/bpdm#530]
Based on the Security Assessment we should introduce rate limiting for Pool and Gate

https://confluence.catena-x.net/pages/viewpage.action?spaceKey=cxsecurity&title=Security+Assessment+-+BPDM+Golden+Record

**Comment by nicoprow** [comment]
Please don't link to infermation which is not publicly accessible. Add the information to the issue so it's available to see for evrybody. If for security reasons that is not possible please get in touch with me again
