### ISSUE TITLE
Security Assessment: Database Integrity Controls (Spike)

### ISSUE THREAD

**Issue by gerlitmcoding** [eclipse-tractusx/bpdm#531]
Based on the Security Assessment we should evaluate how Database Integrity Controls can be realized and also what postgres offers for monitoring changes (Changelog)
https://confluence.catena-x.net/pages/viewpage.action?spaceKey=cxsecurity&title=Security+Assessment+-+BPDM+Golden+Record

**Comment by nicoprow** [comment]
Please don't link to infermation which is not publicly accessible. Add the information to the issue so it's available to see for evrybody. If for security reasons that is not possible please get in touch with me again

**Comment by nicoprow** [comment]
@gerlitmcoding I think database integrity controls depend on how the provider sets up their database. I don't see this in the scope of the BPDM project but rather as many other options as well, in the scope of a professional operator to decide how they want to setup their persistence layer.

**Comment by nicoprow** [comment]
Performance tests for the BPDM orchestrator were introduced here #1071
