### ISSUE TITLE
Orchestrator: Add Authentication/Authorization Logic

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#534]
Currently, the endpoints in the orchestrator application are not authenticated and not assigned any permissions. We should add authorization logic to the application analogous to the BPDM Gate and Pool. The endpoints should be secured with permissions having configurable names.

Suggestions:
- Task Client Controller - Create Task: create_task
- Task Client Controller - Search Task: view_task
- Task Worker Controller: process_task_step_STEPNAME, meaning cleanAndSync,_ process_task_step_poolSync, process_task_stepClean

**Comment by martinfkaeser** [comment]
1) For the Task Worker role I would suggest naming it `process_task_step_STEPNAME` so we can use simple concatenation, e.g. `process_task_step_CleanAndSync`.

2) For the `resolveStepResults` function I suggest adding a `step: TaskStep` property to `TaskStepResultRequest`.
This would be an API change but it would greatly simplify the role check and make it more straightforward.
I think we can still adjust the API. The required changes are only minor.

@nicoprow

**Comment by nicoprow** [comment]
Sure, sounds good to me. No problem to adjust the new Orchestor API if there is good reason for it. So I also think the step enum value would be beneficial here
