### ISSUE TITLE
Workflows: Add report of unit test results

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#583]
Check and implement what are the possibilities to better display test results in Github for our automated test executions during the Github Checks. It would be nice to see the test results very easily visible with what tests are 'green' and 'red'.

**Comment by rainer-exxcellent** [comment]
maybe ths is a good github action for this:

https://github.com/EnricoMi/publish-unit-test-result-action

**Comment by nicoprow** [comment]
Closing due to staleness. This does not seem like a pressing issue
