### ISSUE TITLE
Gate: Add address type filter for generic endpoints

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#634]
When browsing generic business partners I want to filter the business partner records by address type. The result should be paginated, showing the records of the current page, the page number, size and number of total elements that can be paginated through.

**Comment by nicoprow** [comment]
Filter should support multiple values and support all address types plus unspecified (if address type is null).

**Comment by nicoprow** [comment]
For this we should make a breaking change and improve the POST search generic business partner endpoint by getting a search object containing filter fields for externalId list and address types.

**Comment by martinfkaeser** [comment]
Should we use the `AddressType` enum for filtering the business partners? And `null` for unspecified?

So a search request could look like that, when searching for `AdditionalAddress`, `LegalAndSiteMainAddress` and unspecified:
`{ "addressTypes": ["LegalAndSiteMainAddress", "AdditionalAddress", null] }`

Or do we need another `SearchAddressType` enum, probably with this 4 values:
`LegalEntity, Site, Address, Unspecified`

What do you think, @nicoprow ?

**Comment by nicoprow** [comment]
We have decided to not implement that feature for the gate. Extensive filtering is reserved to the Pool for now
