### ISSUE TITLE
Changelog for Chart is outdated

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#641]
Updated the default root level Changelog but in Chart the Changelog seems a bit outdated.
https://github.com/eclipse-tractusx/bpdm/blob/v4.1.0/charts/bpdm/CHANGELOG.md

**Comment by nicoprow** [comment]
Changelog is now up to date in new pre-release version: https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-4.0.0-alpha.0
