### ISSUE TITLE
TRG 7.07 Legal notice for documentation

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#649]
Could you please recheck and add the notice section in your documentation?

https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#documentation

```markdown
## NOTICE

This work is licensed under the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

- SPDX-License-Identifier: Apache-2.0
- SPDX-FileCopyrightText: 202x,202y <MyCompany>
- SPDX-FileCopyrightText: 202x,202y Contributors to the Eclipse Foundation
- Source URL: https://github.com/eclipse-tractusx/<myrepo>
```

### examples: 
- https://github.com/eclipse-tractusx/bpdm/blob/bpdm-3.1.2/docs/decision-records/004-openapi_descriptions.md
- https://github.com/eclipse-tractusx/bpdm/blob/bpdm-3.1.2/docs/edc/README.md
- (https://github.com/eclipse-tractusx/bpdm/blob/bpdm-3.1.2/docs/decision-records/004-openapi_descriptions.md

**Comment by FaGru3n** [comment]
> Add a NOTICE section (post or preamble) into your dedicated documentation file

**Comment by SujitMBRDI** [comment]
> input from the TRG
> 
> > Add a NOTICE section (post or preamble) into your dedicated documentation file
> 
> simple writing each documentation file under your `/docs` folder

@FaGru3n done
