### ISSUE TITLE
Pool: LegalAddress can be Main Site Address

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#657]
Currently, it is not possible in the Pool for a legal address to be also a main site address at the same time. However, according to the BPDM Gate and the golden record process this should be possible. We need to adapt the Pool so a legal address can be a site main address at the same time.

**Comment by alexsilva-CGI** [comment]
I have some doubts regarding this @nicoprow . Currently if an Legal Entity is created and a Site, with the same Address information, two different rows are created on the DB with different BPN's and associations. It seems that it is possible the creation of an Address with both Legal Entity and Site as there are no constraints limiting that.

How would we go, logic wise, to adapt the pool to know if the associated legal address can also be an site main address? Probably by first checking if there similar addresses (Same values) persisted, or is there a field that can be used for this association?

**Comment by nicoprow** [comment]
> I have some doubts regarding this @nicoprow . Currently if an Legal Entity is created and a Site, with the same Address information, two different rows are created on the DB with different BPN's and associations. It seems that it is possible the creation of an Address with both Legal Entity and Site as there are no constraints limiting that.
> 
> How would we go, logic wise, to adapt the pool to know if the associated legal address can also be an site main address? Probably by first checking if there similar addresses (Same values) persisted, or is there a field that can be used for this association?

The Pool doesn't need to infer by itself whether an address is a legal address and/or a site main address. It should be possible to read that from the orchestrator business partner when processing a golden record ticket. There, the address type clearly states whether the address is a legal address, site main address or both.

When it comes to the previous way on how we created business partners in the Pool through the POST and PUT endpoints, I don't think we need to support them anymore. The logic for them can be as is. This is just about the new integration logic with the orchestrator.
