### ISSUE TITLE
TRG 5.07 Dependencies are present and properly configured in the Chart.yaml

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#764]
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07#aligning-dependency-versions

![image](https://github.com/eclipse-tractusx/bpdm/assets/121097161/a18c1c23-a6f4-4cd4-b2af-ff9151bd7012)

Version version: 11.9.13 found in

https://github.com/eclipse-tractusx/bpdm/blob/eb05a1f02b11f6513d3545e6c29131efd4c4c70c/charts/bpdm/Chart.yaml#L56

https://github.com/eclipse-tractusx/bpdm/blob/eb05a1f02b11f6513d3545e6c29131efd4c4c70c/charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml#L32

https://github.com/eclipse-tractusx/bpdm/blob/eb05a1f02b11f6513d3545e6c29131efd4c4c70c/charts/bpdm/charts/bpdm-pool/Chart.yaml#L32

https://github.com/eclipse-tractusx/bpdm/blob/eb05a1f02b11f6513d3545e6c29131efd4c4c70c/charts/bpdm/charts/bpdm-gate/Chart.yaml#L32

**Comment by HeyHardy** [comment]
Is the change to 12.X.X mandatory for Rel. 24.03 or could it be done in next release ? the impact and effort is huge for us, no use case would run cause of an empty database (no BPNs) @rybtim fyi

**Comment by FaGru3n** [comment]
Info to this Check: 
we don't have to upgrade postgres because 15 is still supported until ka 2027. so there's no rush and we won't do it now but after  release "24.03"

**Comment by FaGru3n** [comment]
@HeyHardy as already written in direct chat, will leave the issue open for the next release 👍🏼

**Comment by Siegfriedk** [comment]
@HeyHardy i honestly don't know why we had this misscommunication, but YES we definitly need to align the postgresql version across all produts to be on postgresql 15!!

I'm totally lost why we have not enforced this

**Comment by Siegfriedk** [comment]
@RolaH1t for me this is a hard release blocker FYI

**Comment by Siegfriedk** [comment]
11.9.13 is 14.5.0 This makes it potentially incompatible

**Comment by nicoprow** [comment]
Postgres dependency is updated to 12.12.10 and is now compatible with the TRGs
