### ISSUE TITLE
BPDM dbs update postgress version 11.9 to 12.x.x 

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/bpdm#773]
like written in the TRG the BPDM Postgress databases needs to be updated 
https://github.com/eclipse-tractusx/bpdm/issues/764

https://www.postgresql.org/docs/current/app-pgdump.html

- [ ] with using the helm-hook a migration of data could be considered 
- [x] due date 2 weeks before QG4 Rel. 24.05

**Comment by nicoprow** [comment]
Postgres dependency now updated to the version 12 but no automatic migration performed. However, this limitation is noted in the changelog and release notes.
