### ISSUE TITLE
Workflows: Upload OpenAPI Documentation to Swagger-Hub

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#816]
The BPDM API OpenAPI documentation should be uploaded to SwaggerHub. SwaggerHub should host the BPDM Pool, BPDM Gate and BPDM Orchestrator API documentations. The workflow should upload an unpublished documentation on new pushes to main. When there is a release there should be a published documentation. The version should be given through a variable and when not filled, should be extracted from the pom version.

**Comment by nicoprow** [comment]
The current swaggerhub user registered with this repo does not support more public APIs at the moment

**Comment by Sebastian-Wurm** [comment]
@nicoprow: Talk to DevSecOps how to go on with that.

**Comment by nicoprow** [comment]
This became outdated now, as the Open-API documents should be released in the openAPI-hub of tractusx instead as stated here #1012
