### ISSUE TITLE
Several Issues with the Postman Collection "EDC-BPDM Automated Test"

### ISSUE THREAD

**Issue by Sebastian-Wurm** [eclipse-tractusx/bpdm#824]
### Current Behavior
1. Query catalog not working, because "providerUrl" must be "counterPartyAddress"
2. "GET Sharing States" not working because "BPDM_GATE_API_2" asset must be replaced with variable {{ASSET_GET_SHARING_STATE}}
3. There's no way of checking the status of a contract negotiation -> introduce "Contract Negotiation State" using the negotiation ID returned from "Initiate EDR Negotiation". Store the negotiation ID per OpenAPI resource / endpoint, so that "Contract Negotiation State" can be executed for each OpenAPI resource / endpoint, without initiating new EDR negotiations, when switching between OpenAPI resources / endpoints.
4. Getting the transfer ID in "Query EDRs Cached" uses the last EDR, which might not always be the most current one and might even be expired -> Check for edrState and take the EDR with the highest expiration date
5. worth considering: With all the very similar scripts it might make sense to automatically generate the postman collection, changing only the tiny bits per OpenAPI resource / endpoint

### Expected Behavior
All issues fixed

### Steps To Reproduce
Import Postman collection and send respective requests

**Comment by nicoprow** [comment]
We provide a new Postman collection now: https://github.com/eclipse-tractusx/bpdm/blob/main/docs/postman/EDC%20BPDM%20Consumer.postman_collection.json

This one is a complete overhaul for EDC 0.7 and therefore we do not support the older Postman collection anymore. (It is deleted from the newest docs)
