### ISSUE TITLE
Extension of the documentation, provision of a fully qualified values.xml including KeyCloak dependencies and roles

### ISSUE THREAD

**Issue by thomas-t7** [eclipse-tractusx/bpdm#862]
### Description
When trying to install the Business Partner Data Management (BPDM) project in a SAP Gardener Kubernetes cluster, I would have found it very helpful if a fully qualified configuration had been provided. The provided [values.yaml](https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/charts/bpdm/values.yaml) requires a lot of reverse engineering. In addition, no KeyCloak dependency was defined and no default setup with the necessary roles was provided, as the [DTR team](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/charts/registry/values.yaml) does.

The necessary roles can currently only be determined from your code, documentation would be very helpful here. A recommendation regarding role collections would also be helpful:
[https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/bpdm-pool/src/main/resources/application-auth.yml](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feclipse-tractusx%2Fbpdm%2Fblob%2Frelease%2F5.0.x%2Fbpdm-pool%2Fsrc%2Fmain%2Fresources%2Fapplication-auth.yml&data=05%7C02%7Cthomas.tatzel%40sap.com%7C6bf75506bebc47f41ffd08dc4e3aeef2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638471262273609178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mZ5SS0K0YTt4e%2Bvsr1xtzKVgDG%2BXw592l99YSzewKXg%3D&reserved=0)
[https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/bpdm-orchestrator/src/main/resources/application-auth.yml](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feclipse-tractusx%2Fbpdm%2Fblob%2Frelease%2F5.0.x%2Fbpdm-orchestrator%2Fsrc%2Fmain%2Fresources%2Fapplication-auth.yml&data=05%7C02%7Cthomas.tatzel%40sap.com%7C6bf75506bebc47f41ffd08dc4e3aeef2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638471262273617494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=PU3%2F0Mlm6mi8Aonr0Wg9KueRmB31kKOdn7Es7QaFfK8%3D&reserved=0)
[https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/bpdm-gate/src/main/resources/application-auth.yml](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feclipse-tractusx%2Fbpdm%2Fblob%2Frelease%2F5.0.x%2Fbpdm-gate%2Fsrc%2Fmain%2Fresources%2Fapplication-auth.yml&data=05%7C02%7Cthomas.tatzel%40sap.com%7C6bf75506bebc47f41ffd08dc4e3aeef2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638471262273624655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=MES8%2FGkyvzx9i5w7M2DTp6t9FNbo0U9UnOVM1XLXtCc%3D&reserved=0)

In addition, it would be very helpful if you could link the documentation from the [Business Partner KIT](https://eclipse-tractusx.github.io/docs-kits/category/business-partner-kit) > [Operation View](https://eclipse-tractusx.github.io/docs-kits/kits/Business%20Partner%20Kit/Operation%20View) and update it accordingly.

Currently it takes a lot of time to provision the BPDM project, as only parts are documented and a lot of reverse engineering is necessary to provide an empty BPDM gate + pool for internal tests which I have already discussed internally with @Siegfriedk .

### Acceptance Criteria

- [ ] Provision of fully qualified values.xml
- [ ] Add Keycloak dependencies to values.xml
- [ ] Document Keycloak roles

### Additional Information
Enclosed are my fully qualified [values-bpdm.yaml.zip](https://github.com/eclipse-tractusx/bpdm/files/14956691/values-bpdm.yaml.zip) for reference.

**Comment by nicoprow** [comment]
- The BPDM charts now include a Keycloak dependency and configure a default realm for BPDM services to connect to.
- Documentation about the roles and permissions can now be found in the [arc42](https://github.com/eclipse-tractusx/bpdm/blob/release/6.0.x/docs/arc42/arc42-bpdm.md)

**Comment by nicoprow** [comment]
Closing this issue due to staleness
