### ISSUE TITLE
Geo-data not displaying all digits in the gate

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/bpdm#978]
the geo-data should display all digits written in the pool and input stage from sharing member
 
Latitude: -25.79753 and Longitude: -80.29847
Latitude:  80.29847 and Longitude: -25.79753
Latitude: -80.29847 and Longitude: 25.79753

### Current Behavior
in Longitude only 2 digits after comma are displaying and sometime its rounded.

Latitude: -25.79753 and Longitude: -80.29
Latitude:  80.29847 and Longitude: -25.8
Latitude: -80.29847 and Longitude: 25.79

**Comment by SujitMBRDI** [comment]
@HeyHardy, I tried to replicate this issue, but I couldn't able to see any scenario where the longitude and latitude values are getting rounded of. Technically we are using Float data type for these attributes which is having wide range so rounding off should not happen.
If you have specific test record/data with you then kindly provide to me so I can cross check.

**Comment by babafareed-bikkusab** [comment]
Hi @SujitMBRDI, @nicoprow,

I would like to elaborate the issues which we faced regarding this latitude and longitude fields in our BPDM Gate.
At present we are considering the latitude and longitude value as valid, only if it is having a 6 decimal points. 
When we try to insert a record into our Gate with the values "longitude": -80.212389,
"latitude": -25.79175. 
When we try to fetch that particular record from the Gate, it is returning as "longitude": -80.21239,
"latitude": -25.79176, which results as a invalid Geo coordinates in our case. I understand that here the issue with the data type float, it is automatically rounding it off to the nearest value. But this is creating a confusion for us, even though we give 6 decimal Geo coordinates, as it is returning it as 5 decimal. We will be end up by considering this as invalid Geo coordinates.
Can you please help us regarding this, do you see any risk of considering the latitude, longitude as a string data type.
